[template]
cargo_generate_version = ">=0.21.0"
ignore = ["post-script.rhai"]

[placeholders.gh-username]
default = "LucasPickering"
prompt = "GitHub username (or organization)"
regex = "^[A-Za-z0-9][A-Za-z0-9-]{0,38}$"
type = "string"

[placeholders.project-description]
prompt = "Project description"
type = "string"

[placeholders.rust-version]
default = "1.95.0"
prompt = "Rust version"
type = "string"

[conditional.'crate_type == "bin"'.placeholders.dist]
default = false
prompt = "Set up cargo-dist?"
type = "bool"

[conditional.'crate_type == "lib"']
ignore = ["src/main.rs"]

[conditional.'crate_type == "bin"']
ignore = ["src/lib.rs"]

[conditional.'dist'.hooks]
post = ["post-script.rhai"]
