[package]
name = "{{project-name}}"
description = "{{project-description}}"
version = "0.1.0"
authors = ["{{authors}}"]
keywords = []
repository = "https://github.com/{{gh-username}}/{{project-name}}"
homepage = "https://github.com/{{gh-username}}/{{project-name}}"
edition = "2024"
license = "MIT"
# Keep in sync w/ rust-toolchain.toml
{%- if crate_type == "lib" %}# TODO downgrade MSRV{% endif %}
rust-version = "{{rust-version}}"

[workspace.metadata.release]
pre-release-replacements = [
    { file = "CHANGELOG.md", search = "## \\[Unreleased\\] - ReleaseDate", replace = "## [Unreleased] - ReleaseDate\n\n## [{{version}}] - {{date}}" },
]

[workspace.lints.rust]
async_fn_in_trait = "allow"
unsafe_code = "forbid"

[workspace.lints.clippy]
all = {level = "deny", priority = -1}
pedantic = {level = "warn", priority = -1}

allow_attributes = "deny"
cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
cast_precision_loss = "allow"
cast_sign_loss = "allow"
dbg_macro = "warn"
default_trait_access = "allow"
doc_markdown = "allow"
explicit_deref_methods = "allow"
large_enum_variant = "allow"
map_unwrap_or = "allow"
match_same_arms = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_inception = "allow"
mod_module_files = "deny"
must_use_candidate = "allow"
needless_pass_by_value = "allow"
similar_names = "allow"
single_match = "allow"
too_many_lines = "allow"
unused_self = "allow"
used_underscore_binding = "allow"

[dependencies]

[lints]
workspace = true

{%- if dist %}

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[workspace.metadata.dist]
cargo-dist-version = "0.21.1"
ci = ["github"]
installers = ["shell", "powershell", "homebrew"]
tap = "{{gh-username}}/homebrew-tap"
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "x86_64-pc-windows-msvc",
]
publish-jobs = ["homebrew"]
pr-run-mode = "plan"
install-updater = false
{%- endif %}
