[template]
cargo_generate_version = ">=0.21.0"

[placeholders.crate-name]
prompt = "Crate name"
type = "string"

[placeholders.description]
prompt = "Description"
type = "string"

[conditional.'crate_type == "lib"']
ignore = ["src/main.rs"]

[conditional.'crate_type == "bin"']
ignore = ["src/lib.rs"]
