[package]
authors = {workspace = true}
description = "{{description}}"
edition = {workspace = true}
homepage = {workspace = true}
keywords = {workspace = true}
license = {workspace = true}
name = "{{crate-name}}"
repository = {workspace = true}
rust-version = {workspace = true}
version = {workspace = true}

[dependencies]

[lints]
workspace = true

[package.metadata.release]
tag = false
